config:
  aws:region: us-west-2
  strava-ap-infra:stravaClientId: "200536"
  strava-ap-infra:stravaClientSecret:
    secure: AAABAB63/lzxxU8NnqcqyCtu6kKK4ejel773g+eZJ34POV25FzujWbd0qKghdWLGO2Khin3tQtYfnLjWZuKEHnSuzfNirrxl
